[package]
name = "y2020d19"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2020d19"
path = "src/19.rs"

[dependencies]
aoclib = "0.2.1"
itertools = "0.9.0"
nom = "6.0.1"


[lints]
workspace = true
