[package]
name = "y2018d03"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2018d03"
path = "src/03.rs"

[dependencies]
aoclib = "0.2.1"

[dependencies.nom]
version = "4.1.1"
features = ["verbose-errors"]


[lints]
workspace = true