[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["Hmvp"]
edition = "2018"

[lib]
bench = false

[dependencies]
rust-crypto = "0.2.36"
aoc-runner = "0.2.2"
aoc-runner-derive = "0.2.2"
trees = "0.2.1"
permutohedron = "0.2.4"
crossbeam-channel = "0.4"
crossbeam-utils = "0.7.0"
bytecount = "0.6.0"

[profile.release]
debug = true