[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Hmvp"]
edition = "2018"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
nom = "6.0.1"
strum = { version = "0.20", features = ["derive"] }
itertools = "0.9.0"

[profile.release]
debug = true
lto = true
