[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Hmvp"]
edition = "2018"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"


[profile.release]
debug = true
lto = true