[package]
name = "y2019d25"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2019d25"
path = "src/25.rs"

[dependencies]
aoclib = "0.2.1"
crossbeam-channel = "0.4"
crossbeam-utils = "0.7.0"
compute = {path = "../compute"}
termion = "1.5.4"

[lints]
workspace = true
