[package]
name = "y2020d04"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2020d04"
path = "src/04.rs"

[dependencies]
aoclib = "0.2.1"
nom = "7.1.3"
strum = { version = "0.20", features = ["derive"] }
